sudo: required
language: node_js
node_js:
  - 12

services:
  - docker

before_install:
  - wget -qO- https://toolbelt.heroku.com/install.sh | sh

install:
  - npm install

script: 
  - npm test
  - docker build -t friday-chatbot .

deploy:
  provider : script
  cleanup: false
  script:
    docker login -u $DOCKER_USER -p $DOCKER_PASSWORD;
    docker tag friday-chatbot $DOCKER_USER/friday-chatbot:$TRAVIS_BUILD_NUMBER;
    docker push $DOCKER_USER/friday-chatbot:$TRAVIS_BUILD_NUMBER;
    docker tag friday-chatbot $DOCKER_USER/friday-chatbot:latest;
    docker push $DOCKER_USER/friday-chatbot:latest;
    heroku container:login;
    heroku container:push web -a fridaywebhook;
    heroku container:release web -a fridaywebhook;
  on:
    branch: master