version: '2.2'
services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.6.1
    environment:
      - discovery.type=single-node
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - data:/usr/share/elasticsearch/data
    ports:
      - 9200:9200
      - 9300:9300
    entrypoint:
      - elasticsearch
      - -Ehttp.port=9200
      - -Ehttp.cors.enabled=true
      - -Ehttp.cors.allow-origin=xxx
      - -Ehttp.cors.allow-headers=Content-Type,Content-Length,Authorization
      - -Ehttp.cors.allow-credentials=true

  kibana:
    image: docker.elastic.co/kibana/kibana:7.6.1
    ports: 
      - 5601:5601

volumes:
  data:
